### ISSUE TITLE
Getting password protected sharing link with expiry date

### ISSUE THREAD

**Issue by demin13** [dariobauer/graph-onedrive#16]
Hi @dariobauer and @Shub77
I tried to implement an addition feature for getting a password protected sharing link of [DriveItem](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0) but the post request I had created with the help of [this link](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=javascript) is not able to get the item using its item_id as it is returning fileNotFound in its response_data.

here is my code, please improve it or add the feature mentioned above.

`    @token_required
    def get_sharinglink(self, item_id: str):

        request_url = self._API_URL + "me/drive/items/{}/createLink".format(item_id)
        body = {
            "type": "view",
            "password": "1234",
            "scope": "organization"
            }
        response = httpx.post(request_url, headers=self._headers, json=body)

        response_data = response.json()

        return response_data`
Thanks

**Comment by dariobauer** [comment]
Sharing link functionality differs between personal OneDrive and organisation OneDrive (work/school accounts).

It seems that you are wanting to create a password protected link for an organisation which is not possible:

`The password of the sharing link that is set by the creator. Optional and OneDrive Personal only.`

For personal accounts you can use:

```json
{
  "type": "view",
  "password": "1234",
  "scope": "anonymous"
}
```

For organisation accounts the process would be to first create a sharing link, and then grant permissions to specific users.

I will look at this in more detail and carry out some testing.

**Comment by demin13** [comment]
Okay , then could you please add one functionality which generates sharing link for the organisation onedrive which should have edit or view option.

Thanks

**Comment by dariobauer** [comment]
I have drafted this feature, refer to the branch [sharing-links](https://github.com/dariobauer/graph-onedrive/tree/sharing-links).

You can test and use this development build by installing the branch directly:

```console
pip install https://github.com/dariobauer/graph-onedrive/archive/sharing-links.zip
```

Please let me know if you experience any issues.
This will be included in the next feature release.

**Comment by dariobauer** [comment]
This has been merged into main and will be in the next release.

You can use the development version before then if you are so inclined: `pip install https://github.com/dariobauer/graph-onedrive/archive/main.zip`.

**Comment by demin13** [comment]
Hi @dariobauer 
As I tried to get the sharing link by using this code
`my_drive.create_share_link(item_id="01H56XG2DAWFPVXRN6T5FYXDJRVYZ2WRBA"`
but it raises an exception 
` raise Exception(
Exception: API Error : share link could not be created (Item not found)`

I have already given all the permissions in my azure AD as per the permissions given [here](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online) 
 
I am testing this from a work account.
Also I am not able to make request for [permissions](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/permission?view=odsp-graph-online)
but for [DriveItem](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem?view=odsp-graph-online) everything works fine .

please let me know whether I am getting item not found error by doing some mistakes in calling the API or I am missing something in Microsoft Azure App.

Thanks

**Comment by dariobauer** [comment]
> As I tried to get the sharing link by using this code
> `my_drive.create_share_link(item_id="01H56XG2DAWFPVXRN6T5FYXDJRVYZ2WRBA"`
> but it raises an exception
> ` raise Exception( Exception: API Error : share link could not be created (Item not found)`

This error can occur due to several reasons.

Most likely your work is blocking "anonymous" links, unfortunately the Graph API returns "item not found" in this instance, so this is [noted in the docs](https://github.com/dariobauer/graph-onedrive/blob/main/docs/DOCUMENTATION.md#create_share_link). You can check this by going to the website and manually creating a sharing link, there you will see "Anyone with the link" has been disabled by your organisation.



<img src="https://github.com/dariobauer/graph-onedrive/raw/main/docs/images/link_settings.png" width=350 alt="Screenshot of organisation link settings from the website">

Try specifying the scope:

```python
my_drive.create_share_link(item_id="01H56XG2DAWFPVXRN6T5FYXDJRVYZ2WRBA", scope="organization")
```

> Also I am not able to make request for permissions

I have not yet added permissions methods as there are several so will take some time to add.

**Comment by demin13** [comment]
Yeah Thanks , its perfectly working for personal Accounts.

but I am still getting FileNotFound for Work Account as I provided scope: "organization".

**Comment by dariobauer** [comment]
Can you please confirm:

1. Using the website you can create a shared link for this file?
2. On the website link settings the blue "people in organization with the link" is available?
2. Does `my_drive.detail_item("01H56XG2DAWFPVXRN6T5FYXDJRVYZ2WRBA")` return a valid item? Could you share this response (removing any sensitive data)?

**Comment by demin13** [comment]
yeah sure
> 2. On the website link settings the blue "people in organization with the link" is available?
- yes its available.
> 3. Does `my_drive.detail_item("01H56XG2DAWFPVXRN6T5FYXDJRVYZ2WRBA")` return a valid item? Could you share this response (removing any sensitive data)?
 yeah its returning the details from the above item id 

![image](https://user-images.githubusercontent.com/44312962/140723205-b0c6c51a-584a-42cb-b839-27088fb7680f.png)

If I am trying to make a post request on [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) then there also I am getting 404 response as fileNotFound.
I think if there is any admin consent permissions I am missing or something else.. as I have already provided all the delegated permissions needed for creating sharing link.

**Comment by dariobauer** [comment]
I cannot reproduce this issue (sharing a file `1.docx` in the root of a business OneDrive which blocks anonymous links works fine for me).

Can you please try the following steps:

1. Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and sign in using the business account.
2. Create a query `GET` `v1.0` `https://graph.microsoft.com/v1.0/me/drive/items/{itemid}` to verify that you can access the file.
3. Create a new query `POST` `v1.0` `https://graph.microsoft.com/v1.0/me/drive/items/{itemid}/createLink` with the body `{"type": "view", "scope": "organization"}`

If this does not work then it is not an issue with the any of the Python packages.

**Comment by demin13** [comment]
> I cannot reproduce this issue (sharing a file `1.docx` in the root of a business OneDrive which blocks anonymous links works fine for me).
> 
> Can you please try the following steps:
> 
> 1. Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and sign in using the business account.
> 3. Create a new query `POST` `v1.0` `https://graph.microsoft.com/v1.0/me/drive/items/{itemid}/createLink` with the body `{"type": "view", "scope": "organization"}`
- I am still not able to generate the sharable link by making a post request from graph explorer for my organization. I don't know why but I am trying to find the issue as Everything working fine for personal accounts.
> If you get a `400` series error then it is not an issue with the any of the Python packages.

Yeah Its not the issue of python packages.
btw thanks a lot for the quick responses.
