### ISSUE TITLE
GraphAPI upload Issue

### ISSUE THREAD

**Issue by tanish36** [dariobauer/graph-onedrive#21]
When I am trying to upload the same file I get this error : 

<b>upload session could not be created (A file with the same name is currently being uploaded. Change the filename and try to save again.)</b>

And this error comes randomly but when it comes I need to delete the file from Onedrive Mannually to get this running again
And i am using the same code you have provided for uploading files

**Comment by tanish36** [comment]
This is what I can see in the logs

```
Reading OneDrive configs
Saving refresh token
Requesting upload session
```
and this usually happens when i upload a file x and then i try to upload a other file y

**Comment by dariobauer** [comment]
Hi Udit,

Release v.0.1.0 does not delete the upload_url if an issue is experienced during upload. I assume that this is the case and you are catching this issue in a try block.

Can you please install the development version to see if this addresses your issue?

```console
pip uninstall graph-onedrive
pip install https://github.com/dariobauer/graph-onedrive/archive/main.zip
```

**Comment by tanish36** [comment]
Hi Dario,

I have installed the development version then also I am getting the same error
```
graph_onedrive._onedrive.GraphAPIError: upload session could not be created (A file with the same name is currently being uploaded. Change the filename and try to save again.)
```
I am using this library in the Django project if that is generating some issue you know

**Comment by tanish36** [comment]
```
  File "C:\Users\User\Desktop\Work\Backend-AutomatedDocumentation\automated_documentation\onedrive_save.py", line 29, in save_to_onedrive
    item_id = my_drive.upload_file(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\graph_onedrive\_decorators.py", line 28, in wrapper_token
    wrapped_func = func(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\graph_onedrive\_onedrive.py", line 1286, in upload_file
    self._raise_unexpected_response(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\graph_onedrive\_onedrive.py", line 281, in _raise_unexpected_response
    raise GraphAPIError(f"{message} ({graph_error})")
```

Error Traceback

**Comment by dariobauer** [comment]
Thanks for testing that.

Would you mind providing some context on how you are calling the package within your `onedrive_save.py` file?
- What type of file is it (extension) and how large is the file approx?
- Are you calling the upload_file in a loop?
- Are you trying to upload multiple files at the same time using async?

One other thing to check would be to try upload using the command-line interface in the terminal:
```console
$ graph-onedrive --instance
```

**Comment by tanish36** [comment]
Hi

My code for uploading the file

```
def save_to_onedrive(file_path, doc_id):
    config_path = "config.json"
    config_key = "onedrive"
    my_drive = graph_onedrive.create_from_config_file(config_path, config_key)

    # UPLOAD A FILE
    file_path = file_path
    item_id = my_drive.upload_file(
        file_path,
        if_exists="replace",
        # parent_folder_id="01H56XG2DITYGKN6QZUBDYT2Y6M7VAB3X3",
        verbose=True,
    )
    print(item_id)
    # Updating Django Object
    Document.objects.filter(id=doc_id).update(onedrive_doc_id=item_id)

    # Save the config to retain the refresh token
    graph_onedrive.save_to_config_file(my_drive, config_path, config_key)
    

```

I am uploading Docx type of files which are less than 4MB 
I am not uploading multiple file at a same time uploading a single file at a time through the Django API
Not using aysnc functionality or calling it in a loop

**Comment by tanish36** [comment]
And after waiting for 10-12 min if i hit that API again it will work without this error

**Comment by dariobauer** [comment]
Your code works fine for me.
The 10min time is probably the upload url expiring.
Seems that the issue could be timeout during upload or maybe multiple requests hitting your api?

Can you please add this to your code at the beginning of the function and then see if there are any issues:

```python
# set logging to debug - remove in production
logging.basicConfig(level=logging.DEBUG)
```

**Comment by tanish36** [comment]
Hi Dario

It seems the issue arises when more than one user is trying to upload the same file in a time span of 10 min
any insight how can i resolve this 
@dariobauer

**Comment by dariobauer** [comment]
Uploading the same file in quick succession is not an issue (although this is not an intended use of OneDrive).
It also doesn't matter if you have different users requesting this as the command is executed on the server, not the client.
This code works fine for me (uploading the same file 3 times):

```python
# using the context manager, but you can use `create_from_config_file`
with graph_onedrive.OneDriveManager("config.json", "onedrive") as onedrive:
    for _ in range(3):
        item_id = onedrive.upload_file(file_path, if_exists="replace")
        print(item_id)  # the same id is printed three times
```

I think these are potential ways you could get the issue:
1. You are using an older version of the package. Use `graph-onedrive -V` to check the version is >0.1.0 (eg 0.1.1dev2)
2. A request is made for an upload url when another upload is still in progress. This would happen if you are using any kind of non-blocking processes (asyncio, Celery, Redis, multi-thread, async, coroutines, etc).
3. The first upload experiences an issue (which requests that the upload url is deleted) but then the delete request also fails. This could be caused by a drop in connection and/or timeout.

Please set the logger to debug. If you are not running in the command line then you can [export the logs to a file](https://docs.python.org/3/howto/logging.html#logging-to-a-file).

```python
logging.basicConfig(level=logging.DEBUG)
```

**Comment by tanish36** [comment]
Hi Dario

This issue was happening if you generate the link and then keep the word docx open and then again generate the link
This seems to be issue from Microsoft Graph side if this seems correct to you also we can close this issue
