### ISSUE TITLE
Bug when using download_file with verbose=False

### ISSUE THREAD

**Issue by tulbureandreit** [dariobauer/graph-onedrive#29]
Hello,

When using download_file (file, max_conn, verbose=False), the system returns an error, that a variable was referenced before assignment.

I found that this is a result of a bug: you mis-idented a print at line 1342 in _onedrive.py.

Can you fix it ? Thank you!

Keep up the good work.

**Comment by dariobauer** [comment]
Hi Tulbure, thanks for raising this issue and finding the bug.
I have fixed this by unindenting the `part_name` definition.

Unfortunately the `download_file` method is currently not automatically tested as test are a bit more complex with async. Hopefully test will be added in the future which should make bugs like this avoidable.

This fix will be issued as release 1.3.1 on PyPI in the coming days. You can also install the active dev version using `pip install https://github.com/dariobauer/graph-onedrive/archive/main.zip`.

Thanks
