### ISSUE TITLE
Download file to the specified folder

### ISSUE THREAD

**Issue by mariaboca** [dariobauer/graph-onedrive#31]
Hi Dario,
I want to download files from OneDrive to the specified folder on my computer. Can you help me with this problem? 

Thank you!

**Comment by dariobauer** [comment]
This was not previously possible as files were always downloaded to the current working directory. The workaround was that you could move the file after download.

PR #32 adds functionality to the download_file method for you to specify a destination directory.

Example usage:

```python3
download_folder = Path.home() / "Downloads"
file_id = "01KDJYTEJ3DSJTGTHPTBEI2CAPJNQUDS8Z"

file_path = my_drive.download_file(file_id, dest_dir=download_folder)

```


This feature will be issued as release 1.4.0 on PyPI in the coming days. You can also install the active dev version using `pip install https://github.com/dariobauer/graph-onedrive/archive/main.zip`.

**Comment by mariaboca** [comment]
@dariobauer 
Thank you again, Dario! Great work!
