### ISSUE TITLE
Recursively list children of folder

### ISSUE THREAD

**Issue by roablep** [dariobauer/graph-onedrive#43]
It would be really nice to be able to recursively list children of a OneDrive folder. Something like `list_directory(children=True)`

I've experimented with the API but can't seem to figure out how to make it happen: 
```
https://graph.microsoft.com/v1.0/me/drive/items/<ID>/children?$expand=children

{
  "error": {
    "code": "notSupported",
    "message": "Operation not supported",
    "innerError": {
      "date": "2022-12-17T16:42:47",
      "request-id": "",
      "client-request-id": ""
    }
  }
}
```

**Comment by dariobauer** [comment]
Hi Peter

I have not seen such a feature documented within the Graph docs, so don't think that it is supported server-side.

You could implement something like the below in your script that recursively lists directories, but it will make a bunch of API calls so may cause the API to throttle your account. You may also run into python recursion errors if the structure is very deep.

```python3
from graph_onedrive import OneDriveManager

def list_folder(onedrive_instance, folder_id=None):
    items = onedrive_instance.list_directory(folder_id=folder_id)
    for item in items:
        if "folder" in item.keys():
            if item["folder"]["childCount"] >= 1:
                item["children"] = list_folder(onedrive_instance, folder_id=item["id"])
            else:
                item["children"] = []
    return items

def main():
    with OneDriveManager() as my_drive:
        structure = list_folder(my_drive)
        print(structure)

if __name__ == "__main__":
    SystemExit(main())
```

This solution would require quite a bit of testing before it is added to the package.

**Comment by roablep** [comment]
Thanks Dario. I guess we should close this issue as resolved
